version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: key
      MYSQL_TCP_PORT: 3306
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
     - 3306:3306
    network_mode: host
    expose:
      - 3306
  cassandra:
    image: cassandra:latest
    restart: always
    ports:
      - 7000:7000
      - 9042:9042
    expose:
    - 7000
    - 9042
    volumes:
      - cass-data:/var/lib/cassandra/commitlog
      - cass-data:/var/lib/cassandra/hints
      - cass-data:/var/lib/cassandra/data
      - cass-data:/var/lib/cassandra/saved_caches
      - cass-data:/var/log/cassandra
      
volumes:
  mysql-data:
  cass-data:
