name: Docker Image CI

on:
  push:
    branches: [ stg ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
 
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract Git Tag
      run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Build the Docker image
      env:
        VERSION: ${{ env.GIT_TAG }}
      run: docker build . --file Dockerfile --build-arg BTYPE=github MY_GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}  --tag ${{ env.IMAGE_NAME }}:${{ env.VERSION}}
      
    - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
      run: echo "${{ secrets.MY_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image
      run: |
          IMAGE_ID=ghcr.io/${{ env.IMAGE_NAME }}:${{ env.VERSION}}
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]'
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
    
